
torchrun --standalone --nproc_per_node="gpu" ../../../mace/mace-field/mace/cli/run_train.py \
    --name="MACE-Field-MP-Ferroelectrics-3" \
    --train_file="MP-Ferroelectrics-train.xyz" \
    --test_file="MP-Ferroelectrics-test.xyz" \
    --valid_file="MP-Ferroelectrics-valid.xyz" \
    --E0s="average" \
    --loss='universal_field' \
    --energy_weight=1.0 \
    --forces_weight=100.0 \
    --stress_weight=1.0 \
    --polarization_weight=10.0 \
    --becs_weight=0.0 \
    --polarizability_weight=0.0 \
    --compute_polarization=True \
    --compute_becs=True \
    --compute_polarizability=True \
    --compute_forces=True \
    --compute_stress=True \
    --model="MACEField" \
    --num_channels=128 \
    --num_workers=8 \
    --lr=0.005 \
    --swa \
    --ema \
    --ema_decay=0.995 \
    --scheduler_patience=10 \
    --max_num_epochs=1000 \
    --patience=100 \
    --amsgrad \
    --distributed \
    --device="cuda" \
    --enable_cueq True \
    --seed=23 \
    --default_dtype="float64" \
    --save_cpu \
    --batch_size 2 \
    --valid_batch_size 2 \
    --restart_latest \
    --plot=True \
