# --- run / bookkeeping ---
name: mace-field-mp-0b3-medium-mh
# launcher: torchrun
distributed: true
device: cuda
seed: 123
default_dtype: float32
restart_latest: true
num_workers: 8

# --- data ---
# One head with multiple training files (list); validation taken as a fraction
heads:
  mp-dielectric:
    train_file: ["../Dielectrics/MP-Dielectrics-filtered-train.xyz"]
    valid_file: ["../Dielectrics/MP-Dielectrics-filtered-valid.xyz"]
    test_file: ["../Dielectrics/MP-Dielectrics-filtered-test.xyz"]
  mp-ferroelectric:
    train_file: ["../Ferroelectrics/MP-Ferroelectrics-train.xyz"]
    valid_file: ["../Ferroelectrics/MP-Ferroelectrics-valid.xyz"]
    test_file: ["../Ferroelectrics/MP-Ferroelectrics-test.xyz"]

# Optional replay (foundation) data for multihead finetuning
pt_train_file: mp_traj_selected.xyz
multiheads_finetuning: true  # set true if you actually want replay finetuning

# If you want to use per-element offsets learned by the foundation model
E0s: foundation

# --- model / loss ---
foundation_model: mace-mp-0b3-medium.model
model: MACEField
loss: universal_field

# --- which labels to compute/use ---
compute_forces: true
compute_becs: true
compute_polarization: true
compute_polarizability: true
enable_cueq: true

# --- optimization / training ---
lr: 0.0001
swa: true
ema: true
ema_decay: 0.999
amsgrad: true
batch_size: 1
valid_batch_size: 1
max_num_epochs: 300
patience: 100
enable_cueq: true
save_cpu: true

# matpes labels
energy_weight: 1.0
forces_weight: 100.0
stress_weight: 1.0

# ferroelectric label
polarization_weight: 10.0

# dielectric labels
becs_weight: 100.0
polarizability_weight: 10.0