
torchrun --standalone --nproc_per_node="gpu" ../../../mace/mace-field/mace/cli/run_train.py \
    --name="MACE-field-SiO2" \
    --train_file="SiO2-preprocessed.xyz" \
    --valid_fraction=0.20 \
    --E0s="average" \
    --loss='universal_field' \
    --energy_weight=1.0 \
    --forces_weight=50.0 \
    --stress_weight=1.0 \
    --becs_weight=100.0 \
    --polarizability_weight=200.0 \
    --polarization_weight=10.0 \
    --compute_polarization=True \
    --compute_becs=True \
    --compute_polarizability=True \
    --compute_forces=True \
    --compute_stress=True \
    --model="MACEField" \
    --num_channels=64 \
    --num_workers=8 \
    --lr=0.01 \
    --ema \
    --ema_decay=0.99 \
    --scheduler_patience=10 \
    --patience=100 \
    --max_num_epochs=1000 \
    --amsgrad \
    --distributed \
    --device="cuda" \
    --enable_cueq True \
    --seed=23 \
    --default_dtype="float64" \
    --save_cpu \
    --batch_size 8 \
    --valid_batch_size 8 \
    --restart_latest \
    --plot=True \